from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from gwa_surprise import Ui_DialogSurprise
import resources
import webbrowser


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(507, 447)
        Dialog.setWindowFlags(Qt.CustomizeWindowHint | Qt.WindowCloseButtonHint)
        font = QtGui.QFont()
        font.setPointSize(7)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/macbook_medal_96px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/macbook_medal_96px.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/macbook_medal_96px.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/macbook_medal_96px.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/macbook_medal_96px.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/macbook_medal_96px.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: #2A0C31;color: white;")
        self.label_60 = QtWidgets.QLabel(Dialog)
        self.label_60.setGeometry(QtCore.QRect(300, -10, 111, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("image: url(:/icons/icons/cat-1.png);")
        self.label_60.setText("")
        self.label_60.setObjectName("label_60")
        self.label_59 = QtWidgets.QLabel(Dialog)
        self.label_59.setGeometry(QtCore.QRect(140, 30, 16, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(227, 111, 13, 255), stop:1 rgba(230, 21, 193, 255));")
        self.label_59.setText("")
        self.label_59.setObjectName("label_59")
        self.label_58 = QtWidgets.QLabel(Dialog)
        self.label_58.setGeometry(QtCore.QRect(170, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(227, 111, 13, 255), stop:1 rgba(230, 21, 193, 255));")
        self.label_58.setObjectName("label_58")
        self.about_surprise = QtWidgets.QPushButton(Dialog, clicked=lambda: self.surprise())
        self.about_surprise.setGeometry(QtCore.QRect(100, 30, 51, 31))
        self.about_surprise.setStyleSheet("image: url(:/icons/icons/macbook_medal_96px.png);background-color: #2A0C31;")
        self.about_surprise.setText("")
        self.about_surprise.setObjectName("about_surprise")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(50, 80, 411, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.facebook = QtWidgets.QPushButton(Dialog, clicked=lambda: webbrowser.open('https://web.facebook.com/iamroyland/'))
        self.facebook.setGeometry(QtCore.QRect(30, 400, 41, 31))
        self.facebook.setFocusPolicy(QtCore.Qt.NoFocus)
        self.facebook.setStyleSheet("image: url(:/icons/icons/facebook_96px.png);background-color:transparent;")
        self.facebook.setText("")
        self.facebook.setObjectName("facebook")
        self.blogger = QtWidgets.QPushButton(Dialog, clicked=lambda: webbrowser.open('https://roylandveranopepano.blogspot.com/'))
        self.blogger.setGeometry(QtCore.QRect(110, 400, 41, 31))
        self.blogger.setFocusPolicy(QtCore.Qt.NoFocus)
        self.blogger.setStyleSheet("background-color:transparent;image: url(:/icons/icons/blogger_96px.png);")
        self.blogger.setText("")
        self.blogger.setObjectName("blogger")
        self.instagram = QtWidgets.QPushButton(Dialog, clicked=lambda: webbrowser.open('https://www.instagram.com/iamroyland/'))
        self.instagram.setGeometry(QtCore.QRect(70, 400, 41, 31))
        self.instagram.setFocusPolicy(QtCore.Qt.NoFocus)
        self.instagram.setStyleSheet("background-color:transparent;image: url(:/icons/icons/Instagram logo_96px.png);")
        self.instagram.setText("")
        self.instagram.setObjectName("instagram")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(280, 50, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btn_proceed = QtWidgets.QPushButton(Dialog)
        self.btn_proceed.setGeometry(QtCore.QRect(50, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_proceed.setFont(font)
        self.btn_proceed.setAutoFillBackground(False)
        self.btn_proceed.setStyleSheet("QPushButton#btn_proceed {color: #fff;background-color: #06B4DB;border-radius: 3px;    }QPushButton#btn_proceed:hover:!pressed {background-color: #05A3C7;}")
        self.btn_proceed.setObjectName("btn_proceed")
        self.btn_save = QtWidgets.QPushButton(Dialog)
        self.btn_save.setGeometry(QtCore.QRect(190, 180, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("QPushButton#btn_save {color: #fff;background-color: #0CD498;border-radius: 3px;    }QPushButton#btn_save:hover:!pressed{background-color: #0BC18A;}")
        self.btn_save.setObjectName("btn_save")
        self.btn_calculate = QtWidgets.QPushButton(Dialog)
        self.btn_calculate.setGeometry(QtCore.QRect(340, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.btn_calculate.setFont(font)
        self.btn_calculate.setStyleSheet("QPushButton#btn_calculate {color: #fff;background-color: #FF6F59;border-radius: 3px;    }QPushButton#btn_calculate:hover:!pressed{background-color: #FF6047;}")
        self.btn_calculate.setObjectName("btn_calculate")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 110, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: #39163A;")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(176, 180, 20, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: #39163A;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(325, 180, 20, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: #39163A;")
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(50, 249, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: #39163A;")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(30, 100, 451, 131))
        self.label_14.setStyleSheet("background-color: #39163A;border-radius: 5px;")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(30, 239, 451, 151))
        self.label_15.setStyleSheet("background-color: #39163A;border-radius: 5px;")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(60, 270, 401, 111))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background: transparent;border: 0;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(50, 140, 121, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_3.setGeometry(QtCore.QRect(190, 140, 131, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_4.setGeometry(QtCore.QRect(340, 140, 121, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 440, 571, 21))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(500, 0, 51, 451))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(-45, 0, 51, 451))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.textBrowser_5 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_5.setGeometry(QtCore.QRect(310, 400, 171, 31))
        self.textBrowser_5.setStyleSheet("background: transparent;border: 0;")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.line.raise_()
        self.label_60.raise_()
        self.label_15.raise_()
        self.label_14.raise_()
        self.label_8.raise_()
        self.label_7.raise_()
        self.label_59.raise_()
        self.label_58.raise_()
        self.about_surprise.raise_()
        self.facebook.raise_()
        self.blogger.raise_()
        self.instagram.raise_()
        self.label_3.raise_()
        self.btn_proceed.raise_()
        self.btn_save.raise_()
        self.btn_calculate.raise_()
        self.label_4.raise_()
        self.label_13.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.textBrowser_3.raise_()
        self.textBrowser_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.textBrowser_5.raise_()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def surprise(self):
        self.new = QtWidgets.QWidget()
        self.surprise = Ui_DialogSurprise()
        self.surprise.setupUi(self.new)
        self.new.show()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "About"))
        self.label_58.setText(_translate("Dialog", "GWA Compute"))
        self.label_3.setText(_translate("Dialog", "v1.0"))
        self.btn_proceed.setText(_translate("Dialog", "NEXT"))
        self.btn_save.setText(_translate("Dialog", "SAVE TO DATABASE"))
        self.btn_calculate.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.btn_calculate.setWhatsThis(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_calculate.setText(_translate("Dialog", "CALCULATE"))
        self.label_4.setText(_translate("Dialog", "How to use?"))
        self.label_7.setText(_translate("Dialog", ">"))
        self.label_8.setText(_translate("Dialog", ">"))
        self.label_13.setText(_translate("Dialog", "About"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt; font-weight:600;\">GWA Compute</span><span style=\" font-size:8.25pt;\"> is a desktop application made to automatically compute your General Weighted Average or GWA. It uses the </span><span style=\" font-size:8.25pt; text-decoration: underline;\">5-Point Scale</span><span style=\" font-size:8.25pt;\">, wherein 1.0 is the highest and 5.0 is the lowest (failing mark).</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">GWA Compute is made using </span><span style=\" font-size:8.25pt; text-decoration: underline;\">Python</span><span style=\" font-size:8.25pt;\"> and </span><span style=\" font-size:8.25pt; text-decoration: underline;\">PyQt framework</span><span style=\" font-size:8.25pt;\"> with the help of </span><span style=\" font-size:8.25pt; text-decoration: underline;\">Qt Designer</span><span style=\" font-size:8.25pt;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">© Royland Pepaño</p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">First, fill up the required text </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">fields with correct data.</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">Press this button to save your</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">records in a local database.</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">Finally, press this button to </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">calculate your GWA.</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">Notice:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:6pt;\">    - This is version 1.0, expect a lot of bugs.</span></p></body></html>"))
