from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
import resources
import webbrowser

class Ui_DialogSurprise(object):
    def setupUi(self, DialogSurprise):
        DialogSurprise.setObjectName("DialogSurprise")
        DialogSurprise.setFixedSize(422, 320)
        DialogSurprise.setWindowFlags(Qt.CustomizeWindowHint | Qt.WindowCloseButtonHint)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/macbook_medal_96px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/macbook_medal_96px.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/macbook_medal_96px.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/macbook_medal_96px.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        DialogSurprise.setWindowIcon(icon)
        DialogSurprise.setStyleSheet("background-color: #2A0C31;color: white;")
        self.label_6 = QtWidgets.QLabel(DialogSurprise)
        self.label_6.setGeometry(QtCore.QRect(-11, -10, 21, 341))
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(DialogSurprise)
        self.label_7.setGeometry(QtCore.QRect(411, -10, 21, 361))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(DialogSurprise)
        self.label_8.setGeometry(QtCore.QRect(10, 310, 401, 20))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.textBrowser = QtWidgets.QTextBrowser(DialogSurprise)
        self.textBrowser.setGeometry(QtCore.QRect(40, 60, 341, 101))
        self.textBrowser.setStyleSheet("background: transparent;border: 0;")
        self.textBrowser.setObjectName("textBrowser")
        self.label_60 = QtWidgets.QLabel(DialogSurprise)
        self.label_60.setGeometry(QtCore.QRect(170, -10, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("image: url(:/icons/icons/cat-1.png);")
        self.label_60.setText("")
        self.label_60.setObjectName("label_60")
        self.instagram = QtWidgets.QPushButton(DialogSurprise, clicked=lambda: webbrowser.open('https://www.instagram.com/iamroyland/'))
        self.instagram.setGeometry(QtCore.QRect(190, 200, 31, 31))
        self.instagram.setFocusPolicy(QtCore.Qt.NoFocus)
        self.instagram.setStyleSheet("background-color:transparent;image: url(:/icons/icons/Instagram logo_96px.png);")
        self.instagram.setText("")
        self.instagram.setObjectName("instagram")
        self.facebook = QtWidgets.QPushButton(DialogSurprise, clicked=lambda: webbrowser.open('https://web.facebook.com/iamroyland/'))
        self.facebook.setGeometry(QtCore.QRect(150, 200, 31, 31))
        self.facebook.setFocusPolicy(QtCore.Qt.NoFocus)
        self.facebook.setStyleSheet("image: url(:/icons/icons/facebook_96px.png);background-color:transparent;")
        self.facebook.setText("")
        self.facebook.setObjectName("facebook")
        self.blogger = QtWidgets.QPushButton(DialogSurprise, clicked=lambda: webbrowser.open('https://roylandveranopepano.blogspot.com/'))
        self.blogger.setGeometry(QtCore.QRect(230, 200, 31, 31))
        self.blogger.setFocusPolicy(QtCore.Qt.NoFocus)
        self.blogger.setStyleSheet("background-color:transparent;image: url(:/icons/icons/blogger_96px.png);")
        self.blogger.setText("")
        self.blogger.setObjectName("blogger")
        self.label_4 = QtWidgets.QLabel(DialogSurprise)
        self.label_4.setGeometry(QtCore.QRect(160, 170, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: #2A0C31;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(DialogSurprise)
        self.label_5.setGeometry(QtCore.QRect(160, 280, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: #2A0C31;")
        self.label_5.setObjectName("label_5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(DialogSurprise)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 250, 381, 41))
        self.textBrowser_2.setStyleSheet("background: transparent;border: 0;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_60.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.textBrowser.raise_()
        self.instagram.raise_()
        self.facebook.raise_()
        self.blogger.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.textBrowser_2.raise_()
        self.retranslateUi(DialogSurprise)
        QtCore.QMetaObject.connectSlotsByName(DialogSurprise)

    def retranslateUi(self, DialogSurprise):
        _translate = QtCore.QCoreApplication.translate
        DialogSurprise.setWindowTitle(_translate("DialogSurprise", "Surprise!"))
        self.textBrowser.setHtml(_translate("DialogSurprise", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:26pt; font-weight:600;\">HOW DID YOU</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:26pt; font-weight:600;\">FIND ME?</span></p></body></html>"))
        self.label_4.setText(_translate("DialogSurprise", "Meet the Developer"))
        self.label_5.setText(_translate("DialogSurprise", "© July - August 2021"))
        self.textBrowser_2.setHtml(_translate("DialogSurprise", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">GWA Compute is an offline desktop application enabling users to </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">store and calculate their grades on their device.</span></p></body></html>"))